language: python
sudo: false
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
before_script:
- python manage.py migrate
script:
- py.test
after_success:
- coveralls
